/* ===== Cofre de acessos (compartilhado cliente/admin) ===== */
const CRED_ICON = { 'Redes sociais': '◎', 'Anúncios': '◆', 'Google': 'G', 'Site': '⌂', 'E-mail': '✉', 'Atendimento': '☏', 'Comercial': '▲', 'Design': '✦' };
let CRED = { list: [], presets: [], company: null };
async function credLoad(companyId) { const [{ data: l }, { data: p }] = await Promise.all([sb.from('company_credentials').select('*').eq('company_id', companyId).order('category').order('label'), sb.from('credential_presets').select('*').order('sort')]); CRED = { list: l || [], presets: p || [], company: companyId }; return CRED; }
function credCard(c, admin) { const badge = c.status === 'requested' ? '<span class="badge warn">⏳ aguardando criação</span>' : c.status === 'created' ? '<span class="badge ok">✓ criada pela equipe</span>' : '';
  const pending = c.status === 'requested';
  return `<div class="card cred ${c.status}"><div class="cred-h"><span class="cred-ic">${CRED_ICON[c.category] || '•'}</span><div style="min-width:0"><b>${esc(c.label)}</b><small>${esc(c.category || '')}</small></div>${badge}</div>
    ${pending ? `<p class="hint" style="margin:10px 0 0">${admin ? 'Pedido em ' + dtShort(c.requested_at.slice(0, 10)) + (c.notes ? ' · ' + esc(c.notes) : '') : 'A equipe foi avisada e vai criar esta conta. Os dados aparecem aqui assim que estiver pronta.'}</p>${admin ? `<button class="btn sm primary" style="margin-top:10px" onclick="credFulfill('${c.id}')">Criar e enviar dados</button>` : ''}` : `
    <div class="cred-f"><span>Login</span><code>${esc(c.login || '–')}</code>${c.login ? `<button class="btn sm ghost" onclick="navigator.clipboard.writeText(${JSON.stringify(c.login).replace(/"/g, '&quot;')});toast('Login copiado','ok')">Copiar</button>` : ''}</div>
    <div class="cred-f"><span>Senha</span><code id="pw_${c.id}">••••••••</code><button class="btn sm ghost" onclick="credReveal('${c.id}',this)">Mostrar</button><button class="btn sm ghost" onclick="credCopy('${c.id}')">Copiar</button></div>
    ${c.url ? `<div class="cred-f"><span>Link</span><a href="${esc(c.url)}" target="_blank" rel="noopener" style="color:var(--accent2);overflow:hidden;text-overflow:ellipsis;white-space:nowrap">${esc(c.url.replace(/^https?:\/\//, ''))}</a></div>` : ''}
    ${c.notes ? `<p class="hint" style="margin-top:8px">${esc(c.notes)}</p>` : ''}
    <div class="cred-a"><span class="mono">atualizado ${dtShort(c.updated_at.slice(0, 10))}</span><span style="flex:1"></span><button class="btn sm ghost" onclick="credEdit('${c.id}')">Editar</button><button class="btn sm danger" onclick="credDelete('${c.id}')">×</button></div>`}</div>`; }
function credGrid(admin) { const byCat = {}; CRED.list.forEach(c => (byCat[c.category || 'Outros'] = byCat[c.category || 'Outros'] || []).push(c));
  const missing = CRED.presets.filter(p => !CRED.list.some(c => c.preset_key === p.key));
  return `${missing.length ? `<div class="card" style="margin-bottom:14px"><h3>Adicionar rápido</h3><div class="chips">${missing.map(p => `<span class="chip-btn" onclick="credEdit(null,'${p.key}')">+ ${esc(p.label)}</span>`).join('')}</div></div>` : ''}
    ${CRED.list.length ? Object.entries(byCat).map(([cat, arr]) => `<h3 style="margin:18px 0 10px;font-size:15px;color:var(--muted)">${esc(cat)}</h3><div class="cred-grid">${arr.map(c => credCard(c, admin)).join('')}</div>`).join('') : '<div class="card empty"><b>Nenhum acesso guardado ainda</b>Use os atalhos acima ou "Adicionar acesso".</div>'}`; }
async function credReveal(id, btn) { const el = $('#pw_' + id); if (el.dataset.open) { el.textContent = '••••••••'; delete el.dataset.open; btn.textContent = 'Mostrar'; return; } const { data, error } = await sb.rpc('credential_reveal', { p_id: id }); if (error) return toast(error.message, 'bad'); el.textContent = data || '(sem senha)'; el.dataset.open = 1; btn.textContent = 'Ocultar'; }
async function credCopy(id) { const { data, error } = await sb.rpc('credential_reveal', { p_id: id }); if (error) return toast(error.message, 'bad'); if (!data) return toast('Sem senha salva', 'bad'); await navigator.clipboard.writeText(data); toast('Senha copiada', 'ok'); }
function credEdit(id, presetKey) { const c = CRED.list.find(x => x.id === id) || {}; const pr = CRED.presets.find(p => p.key === (presetKey || c.preset_key)) || {};
  modal(`<h2>${id ? 'Editar acesso' : 'Novo acesso'}</h2><div class="sub">A senha é guardada criptografada. Só quem tem permissão em Acessos e senhas consegue ver.</div>
  ${id ? '' : `<label class="f"><span>Tipo de conta</span><select id="cr_p" onchange="const p=CRED.presets.find(x=>x.key===this.value)||{};$('#cr_l').value=p.label||'';$('#cr_u').value=p.url||'';$('#cr_c').value=p.category||'Outros'"><option value="">Outro (personalizado)</option>${CRED.presets.map(p => `<option value="${p.key}" ${p.key === pr.key ? 'selected' : ''}>${esc(p.label)}</option>`).join('')}</select></label>`}
  <div class="row2"><label class="f"><span>Nome</span><input id="cr_l" value="${esc(c.label || pr.label || '')}"></label><label class="f"><span>Categoria</span><input id="cr_c" value="${esc(c.category || pr.category || 'Outros')}"></label></div>
  <label class="f"><span>Login / e-mail / usuário</span><input id="cr_lg" value="${esc(c.login || '')}" autocomplete="off"></label>
  <label class="f"><span>Senha ${id ? '(deixe em branco para manter a atual)' : ''}</span><div style="display:flex;gap:8px"><input id="cr_pw" type="password" autocomplete="new-password"><button class="btn sm ghost" type="button" onclick="const i=$('#cr_pw');i.type=i.type==='password'?'text':'password'">👁</button></div></label>
  <label class="f"><span>Link de acesso</span><input id="cr_u" value="${esc(c.url || pr.url || '')}"></label><label class="f"><span>Observações (2FA, e-mail de recuperação...)</span><textarea id="cr_n">${esc(c.notes || '')}</textarea></label>
  <div class="md-actions"><button class="btn ghost" onclick="closeModal()">Cancelar</button><button class="btn primary" onclick="credSave('${id || ''}')">Salvar</button></div>`); }
async function credSave(id) { const label = $('#cr_l').value.trim(); if (!label) return toast('Dê um nome ao acesso', 'bad'); const pw = $('#cr_pw').value;
  const { error } = await sb.rpc('credential_save', { p_id: id || null, p_company: CRED.company, p_label: label, p_category: $('#cr_c').value.trim() || 'Outros', p_url: $('#cr_u').value.trim() || null, p_login: $('#cr_lg').value.trim() || null, p_password: pw ? pw : (id ? null : null), p_notes: $('#cr_n').value.trim() || null, p_preset: id ? null : ($('#cr_p')?.value || null) });
  if (error) return toast(error.message, 'bad'); closeModal(); toast('Acesso salvo', 'ok'); route(); }
async function credDelete(id) { if (!confirm('Excluir este acesso? A senha salva será apagada.')) return; const { error } = await sb.from('company_credentials').delete().eq('id', id); if (error) return toast(error.message, 'bad'); toast('Acesso excluído', 'ok'); route(); }
function credRequest() { const have = new Set(CRED.list.map(c => c.preset_key)); modal(`<h2>Preciso que criem uma conta</h2><div class="sub">Escolha a conta. A equipe Ben Hur Andrade é avisada, cria e os dados aparecem aqui em verde.</div>
  <label class="f"><span>Conta</span><select id="rq_p">${CRED.presets.map(p => `<option value="${p.key}" ${have.has(p.key) ? 'disabled' : ''}>${esc(p.label)}${have.has(p.key) ? ' (já existe)' : ''}</option>`).join('')}<option value="">Outra (descreva abaixo)</option></select></label>
  <label class="f"><span>Nome (se for outra)</span><input id="rq_l"></label><label class="f"><span>Observações (e-mail que deve ser usado, nome da página...)</span><textarea id="rq_n"></textarea></label>
  <div class="md-actions"><button class="btn ghost" onclick="closeModal()">Cancelar</button><button class="btn primary" onclick="credRequestSend()">Pedir criação</button></div>`); }
async function credRequestSend() { const p = $('#rq_p').value || null, l = $('#rq_l').value.trim(); if (!p && !l) return toast('Escolha a conta ou descreva', 'bad'); const { error } = await sb.rpc('credential_request', { p_company: CRED.company, p_preset: p, p_label: l || null, p_notes: $('#rq_n').value.trim() || null }); if (error) return toast(error.message, 'bad'); closeModal(); toast('Pedido enviado para a equipe', 'ok'); route(); }
function credFulfill(id) { const c = CRED.list.find(x => x.id === id) || (window._contas || []).find(x => x.id === id) || {}; modal(`<h2>Criar conta: ${esc(c.label || '')}</h2><div class="sub">${esc(c.companies?.name || '')}${c.notes ? ' · pedido: ' + esc(c.notes) : ''}. Ao salvar, aparece em verde para o cliente com estes dados.</div>
  <label class="f"><span>Login / e-mail / usuário</span><input id="ff_l" autocomplete="off"></label><label class="f"><span>Senha</span><div style="display:flex;gap:8px"><input id="ff_p" type="text" autocomplete="off"><button class="btn sm ghost" type="button" onclick="$('#ff_p').value=Array.from(crypto.getRandomValues(new Uint32Array(3))).map(n=>n.toString(36)).join('').slice(0,14)+'#9'">Gerar</button></div></label>
  <label class="f"><span>Link de acesso</span><input id="ff_u" value="${esc(c.url || '')}"></label><label class="f"><span>Observações para o cliente</span><textarea id="ff_n"></textarea></label>
  <div class="md-actions"><button class="btn ghost" onclick="closeModal()">Cancelar</button><button class="btn primary" onclick="credFulfillSave('${id}')">Marcar como criada</button></div>`); }
async function credFulfillSave(id) { if (!$('#ff_l').value.trim()) return toast('Informe o login', 'bad'); const { error } = await sb.rpc('credential_fulfill', { p_id: id, p_login: $('#ff_l').value.trim(), p_password: $('#ff_p').value, p_url: $('#ff_u').value.trim(), p_notes: $('#ff_n').value.trim() }); if (error) return toast(error.message, 'bad'); closeModal(); toast('Conta criada e liberada para o cliente', 'ok'); route(); }
